// Input all hero information below. Maube use ChatGPT?
import { heroList } from "../types/types";

export const tankList: heroList = {
  role: "tank",
  heroes: [
    {
      name: "Warrior 1",
      armour: 5,
      damage: 3,
      healing: 0,
      health: 5,
      points: 13,
      grade: "best",
    },
    {
      name: "Warrior 2",
      armour: 5,
      damage: 3,
      healing: 0,
      health: 4,
      points: 12,
      grade: "",
    },
    {
      name: "Warrior 3",
      armour: 5,
      damage: 2,
      healing: 0,
      health: 5,
      points: 12,
      grade: "",
    },
    {
      name: "Warrior 4",
      armour: 5,
      damage: 2,
      healing: 0,
      health: 4,
      points: 11,
      grade: "",
    },
    {
      name: "Warrior 5",
      armour: 4,
      damage: 3,
      healing: 0,
      health: 5,
      points: 12,
      grade: "",
    },
    {
      name: "Warrior 6",
      armour: 4,
      damage: 3,
      healing: 0,
      health: 4,
      points: 11,
      grade: "",
    },
    {
      name: "Warrior 7",
      armour: 4,
      damage: 2,
      healing: 0,
      health: 5,
      points: 11,
      grade: "",
    },
    {
      name: "Warrior 8",
      armour: 4,
      damage: 2,
      healing: 0,
      health: 4,
      points: 10,
      grade: "worst",
    },
    {
      name: "Barbarian 5",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 4,
      points: 11,
      grade: "best",
    },
    {
      name: "Barbarian 6",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 3,
      points: 10,
      grade: "",
    },
    {
      name: "Barbarian 7",
      armour: 2,
      damage: 4,
      healing: 0,
      health: 2,
      points: 10,
      grade: "",
    },
    {
      name: "Barbarian 8",
      armour: 2,
      damage: 4,
      healing: 0,
      health: 3,
      points: 9,
      grade: "worst",
    },
    {
      name: "Druid 9",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 5,
      points: 12,
      grade: "best",
    },
    {
      name: "Druid 10",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 4,
      points: 11,
      grade: "worst",
    },
    {
      name: "Paladin 1",
      armour: 4,
      damage: 3,
      healing: 1,
      health: 4,
      points: 12,
      grade: "best",
    },
    {
      name: "Paladin 2",
      armour: 4,
      damage: 2,
      healing: 1,
      health: 4,
      points: 11,
      grade: "",
    },
    {
      name: "Paladin 3",
      armour: 3,
      damage: 3,
      healing: 1,
      health: 4,
      points: 11,
      grade: "",
    },
    {
      name: "Paladin 4",
      armour: 3,
      damage: 2,
      healing: 1,
      health: 4,
      points: 12,
      grade: "worst",
    },
  ],
};

export const dpsList: heroList = {
  role: "dps",
  heroes: [
    {
      name: "Rogue 1",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 3,
      points: 10,
      grade: "best",
    },
    {
      name: "Rogue 2",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 2,
      points: 9,
      grade: "",
    },
    {
      name: "Rogue 3",
      armour: 3,
      damage: 3,
      healing: 0,
      health: 3,
      points: 9,
      grade: "",
    },
    {
      name: "Rogue 4",
      armour: 3,
      damage: 3,
      healing: 0,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Rogue 5",
      armour: 2,
      damage: 4,
      healing: 0,
      health: 3,
      points: 9,
      grade: "",
    },
    {
      name: "Rogue 6",
      armour: 2,
      damage: 4,
      healing: 0,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Rogue 7",
      armour: 2,
      damage: 3,
      healing: 0,
      health: 3,
      points: 8,
      grade: "",
    },
    {
      name: "Rogue 8",
      armour: 2,
      damage: 3,
      healing: 0,
      health: 2,
      points: 7,
      grade: "worst",
    },
    {
      name: "Ranger 1",
      armour: 2,
      damage: 5,
      healing: 0,
      health: 3,
      points: 10,
      grade: "best",
    },
    {
      name: "Ranger 2",
      armour: 2,
      damage: 5,
      healing: 0,
      health: 2,
      points: 9,
      grade: "",
    },
    {
      name: "Ranger 3",
      armour: 1,
      damage: 5,
      healing: 0,
      health: 3,
      points: 9,
      grade: "",
    },
    {
      name: "Ranger 4",
      armour: 1,
      damage: 5,
      healing: 0,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Ranger 5",
      armour: 2,
      damage: 4,
      healing: 0,
      health: 3,
      points: 9,
      grade: "",
    },
    {
      name: "Ranger 6",
      armour: 2,
      damage: 4,
      healing: 0,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Ranger 7",
      armour: 1,
      damage: 4,
      healing: 0,
      health: 3,
      points: 8,
      grade: "",
    },
    {
      name: "Ranger 8",
      armour: 1,
      damage: 4,
      healing: 0,
      health: 2,
      points: 7,
      grade: "worst",
    },
    {
      name: "Wizard 1",
      armour: 0,
      damage: 5,
      healing: 0,
      health: 2,
      points: 7,
      grade: "best",
    },
    {
      name: "Wizard 2",
      armour: 0,
      damage: 5,
      healing: 0,
      health: 1,
      points: 6,
      grade: "",
    },
    {
      name: "Wizard 3",
      armour: 0,
      damage: 4,
      healing: 0,
      health: 2,
      points: 6,
      grade: "",
    },
    {
      name: "Wizard 4",
      armour: 0,
      damage: 4,
      healing: 0,
      health: 1,
      points: 5,
      grade: "worst",
    },
    {
      name: "Monk 1",
      armour: 2,
      damage: 3,
      healing: 1,
      health: 4,
      points: 10,
      grade: "best",
    },
    {
      name: "Monk 2",
      armour: 2,
      damage: 3,
      healing: 1,
      health: 3,
      points: 9,
      grade: "",
    },
    {
      name: "Monk 3",
      armour: 1,
      damage: 3,
      healing: 1,
      health: 4,
      points: 9,
      grade: "",
    },
    {
      name: "Monk 4",
      armour: 1,
      damage: 3,
      healing: 1,
      health: 3,
      points: 8,
      grade: "",
    },
    {
      name: "Monk 5",
      armour: 0,
      damage: 3,
      healing: 1,
      health: 4,
      points: 8,
      grade: "",
    },
    {
      name: "Monk 6",
      armour: 0,
      damage: 3,
      healing: 1,
      health: 3,
      points: 7,
      grade: "worst",
    },
    {
      name: "Barbarian 1",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 5,
      points: 12,
      grade: "best",
    },
    {
      name: "Barbarian 2",
      armour: 3,
      damage: 4,
      healing: 0,
      health: 4,
      points: 11,
      grade: "",
    },
    {
      name: "Barbarian 3",
      armour: 3,
      damage: 3,
      healing: 0,
      health: 5,
      points: 11,
      grade: "",
    },
    {
      name: "Barbarian 4",
      armour: 3,
      damage: 3,
      healing: 0,
      health: 4,
      points: 10,
      grade: "worst",
    },
    {
      name: "Paladin 5",
      armour: 3,
      damage: 4,
      healing: 1,
      health: 4,
      points: 12,
      grade: "best",
    },
    {
      name: "Paladin 6",
      armour: 3,
      damage: 4,
      healing: 1,
      health: 3,
      points: 11,
      grade: "",
    },
    {
      name: "Paladin 7",
      armour: 3,
      damage: 3,
      healing: 1,
      health: 4,
      points: 11,
      grade: "",
    },
    {
      name: "Paladin 8",
      armour: 3,
      damage: 3,
      healing: 1,
      health: 3,
      points: 10,
      grade: "worst",
    },
  ],
};

export const healerList: heroList = {
  role: "healer",
  heroes: [
    {
      name: "Bard 1",
      armour: 1,
      damage: 2,
      healing: 5,
      health: 2,
      points: 10,
      grade: "best",
    },
    {
      name: "Bard 2",
      armour: 1,
      damage: 1,
      healing: 5,
      health: 2,
      points: 9,
      grade: "",
    },
    {
      name: "Bard 3",
      armour: 1,
      damage: 2,
      healing: 5,
      health: 1,
      points: 9,
      grade: "",
    },
    {
      name: "Bard 4",
      armour: 1,
      damage: 1,
      healing: 5,
      health: 1,
      points: 8,
      grade: "",
    },
    {
      name: "Bard 5",
      armour: 0,
      damage: 2,
      healing: 5,
      health: 2,
      points: 9,
      grade: "",
    },
    {
      name: "Bard 6",
      armour: 0,
      damage: 1,
      healing: 5,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Bard 7",
      armour: 0,
      damage: 2,
      healing: 5,
      health: 1,
      points: 8,
      grade: "",
    },
    {
      name: "Bard 8",
      armour: 0,
      damage: 1,
      healing: 5,
      health: 1,
      points: 7,
      grade: "worst",
    },
    {
      name: "Druid 1",
      armour: 2,
      damage: 2,
      healing: 5,
      health: 3,
      points: 12,
      grade: "best",
    },
    {
      name: "Druid 2",
      armour: 2,
      damage: 2,
      healing: 5,
      health: 2,
      points: 11,
      grade: "",
    },
    {
      name: "Druid 3",
      armour: 2,
      damage: 2,
      healing: 4,
      health: 3,
      points: 11,
      grade: "",
    },
    {
      name: "Druid 4",
      armour: 2,
      damage: 2,
      healing: 4,
      health: 2,
      points: 10,
      grade: "",
    },
    {
      name: "Druid 5",
      armour: 2,
      damage: 1,
      healing: 5,
      health: 3,
      points: 11,
      grade: "",
    },
    {
      name: "Druid 6",
      armour: 2,
      damage: 1,
      healing: 5,
      health: 2,
      points: 10,
      grade: "",
    },
    {
      name: "Druid 7",
      armour: 2,
      damage: 1,
      healing: 4,
      health: 3,
      points: 10,
      grade: "",
    },
    {
      name: "Druid 8",
      armour: 2,
      damage: 1,
      healing: 4,
      health: 2,
      points: 9,
      grade: "worst",
    },
    {
      name: "Priest 1",
      armour: 0,
      damage: 2,
      healing: 5,
      health: 2,
      points: 9,
      grade: "best",
    },
    {
      name: "Priest 2",
      armour: 0,
      damage: 2,
      healing: 5,
      health: 1,
      points: 8,
      grade: "",
    },
    {
      name: "Priest 3",
      armour: 0,
      damage: 2,
      healing: 4,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Priest 4",
      armour: 0,
      damage: 2,
      healing: 4,
      health: 1,
      points: 7,
      grade: "",
    },
    {
      name: "Priest 5",
      armour: 0,
      damage: 1,
      healing: 5,
      health: 2,
      points: 8,
      grade: "",
    },
    {
      name: "Priest 6",
      armour: 0,
      damage: 1,
      healing: 5,
      health: 1,
      points: 7,
      grade: "",
    },
    {
      name: "Priest 7",
      armour: 0,
      damage: 1,
      healing: 4,
      health: 2,
      points: 7,
      grade: "",
    },
    {
      name: "Priest 8",
      armour: 0,
      damage: 1,
      healing: 4,
      health: 1,
      points: 6,
      grade: "worst",
    },
    {
      name: "Paladin 9",
      armour: 3,
      damage: 2,
      healing: 4,
      health: 3,
      points: 12,
      grade: "best",
    },
    {
      name: "Paladin 10",
      armour: 2,
      damage: 2,
      healing: 4,
      health: 3,
      points: 11,
      grade: "",
    },
    {
      name: "Paladin 11",
      armour: 3,
      damage: 2,
      healing: 3,
      health: 3,
      points: 11,
      grade: "",
    },
    {
      name: "Paladin 12",
      armour: 2,
      damage: 2,
      healing: 3,
      health: 3,
      points: 10,
      grade: "worst",
    },
  ],
};
